spring:
    application:
        name: configserver
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/neeravbhaskarla/articleconfigfiles.git
                    clone-on-start: true
eureka:
    client:
        service-url:
            defaultZone: "${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}"
server:
    port: 8888
