server:
    port: 8761

spring:
  cloud:
    config:
      import: optional:configserver:http://configserver:8888
      
eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
